networks:
  gl-swarm-net:
    external: true

volumes:
  os01-data:
    driver: local
    driver_opts:
      type: none
      device: /home/admin/mnt-glusterfs/opensearch/os01-data
      o: bind
  os02-data:
    driver: local
    driver_opts:
      type: none
      device: /home/admin/mnt-glusterfs/opensearch/os02-data
      o: bind
  os03-data:
    driver: local
    driver_opts:
      type: none
      device: /home/admin/mnt-glusterfs/opensearch/os03-data
      o: bind

services:
  opensearch01:
    image: opensearchproject/opensearch:2.15.0
    hostname: os01
    volumes:
      - os01-data:/usr/share/opensearch/data
      #- "./certs:/usr/share/opensearch/config/certificates:ro"
    ports:
      - target: 9200
        published: 9201
        protocol: tcp
        mode: host
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "cluster.name=opensearch-cluster"
      - "node.name=os01"
      - "discovery.seed_hosts=opensearch01,opensearch02,opensearch03"
      - "cluster.initial_master_nodes=os01,os02,os03"
      - "bootstrap.memory_lock=true"
#      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
      # Can generate a password for `OPENSEARCH_INITIAL_ADMIN_PASSWORD` using a linux device via
      # tr -dc A-Z-a-z-0-9_@#%^-_=+  devurandom  head -c${1-32}
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=Chocolate1-Strawberry-Opacity-Lemon"
      - "network.host=0.0.0.0"
      #plugins.security.ssl.transport.pemkey_filepath: certificates/os01/os01.key # relative path
      #plugins.security.ssl.transport.pemcert_filepath: certificates/os01/os01.pem
      #plugins.security.ssl.http.pemkey_filepath: certificates/os01/os01.key
      #plugins.security.ssl.http.pemcert_filepath: certificates/os01/os01.pem
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - gl-swarm-net
    deploy:
      placement:
        constraints:
          - node.hostname == gl-swarm-01

  opensearch02:
    image: opensearchproject/opensearch:2.15.0
    hostname: os02
    volumes:
      - os02-data:/usr/share/opensearch/data
      #- "./certs:/usr/share/opensearch/config/certificates:ro"
    ports:
      - target: 9200
        published: 9202
        protocol: tcp
        mode: host
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "cluster.name=opensearch-cluster"
      - "node.name=os02"
      - "discovery.seed_hosts=opensearch01,opensearch02,opensearch03"
      - "cluster.initial_master_nodes=os01,os02,os03"
      - "bootstrap.memory_lock=true"
 #     - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
      # Can generate a password for `OPENSEARCH_INITIAL_ADMIN_PASSWORD` using a linux device via
      # tr -dc A-Z-a-z-0-9_@#%^-_=+  devurandom  head -c${1-32}
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=Chocolate1-Strawberry-Opacity-Lemon"
      - "network.host=0.0.0.0"
      #plugins.security.ssl.transport.pemkey_filepath: certificates/os01/os01.key # relative path
      #plugins.security.ssl.transport.pemcert_filepath: certificates/os01/os01.pem
      #plugins.security.ssl.http.pemkey_filepath: certificates/os01/os01.key
      #plugins.security.ssl.http.pemcert_filepath: certificates/os01/os01.pem
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - gl-swarm-net
    deploy:
      placement:
        constraints:
          - node.hostname == gl-swarm-02

  opensearch03:
    image: opensearchproject/opensearch:2.15.0
    hostname: os03
    volumes:
      - os03-data:/usr/share/opensearch/data
      #- "./certs:/usr/share/opensearch/config/certificates:ro"
    ports:
      - target: 9200
        published: 9203
        protocol: tcp
        mode: host
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "cluster.name=opensearch-cluster"
      - "node.name=os03"
      - "discovery.seed_hosts=opensearch01,opensearch02,opensearch03"
      - "cluster.initial_master_nodes=os01,os02,os03"
      - "bootstrap.memory_lock=true"
  #    - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
      # Can generate a password for `OPENSEARCH_INITIAL_ADMIN_PASSWORD` using a linux device via
      # tr -dc A-Z-a-z-0-9_@#%^-_=+  devurandom  head -c${1-32}
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=Chocolate1-Strawberry-Opacity-Lemon"
      - "network.host=0.0.0.0"
      #plugins.security.ssl.transport.pemkey_filepath: certificates/os01/os01.key # relative path
      #plugins.security.ssl.transport.pemcert_filepath: certificates/os01/os01.pem
      #plugins.security.ssl.http.pemkey_filepath: certificates/os01/os01.key
      #plugins.security.ssl.http.pemcert_filepath: certificates/os01/os01.pem
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - gl-swarm-net
    deploy:
      placement:
        constraints:
          - node.hostname == gl-swarm-03
